version: '3'

services:
  web:
    image: peckadesign/php:7.4-dev
    ports:
      - 80
    volumes:
      - ./.docker/web/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/web/apache/conf:/etc/apache2/sites-enabled
      - ./:/var/www/html:cached

  composer:
    image: peckadesign/php:7.4-dev
    entrypoint: composer
    command: install
    volumes:
      - ./:/var/www/html:cached
